#!/usr/bin/env bash
# Reproducible install of the community neuroimaging reference tools (AFNI +
# FSL) used as registration gold standards by the perf-bench registration
# cases. These live on /scratch, which is EPHEMERAL (it can vanish if the box
# is reprovisioned) -- this script (committed to the repo) is the durable
# recipe to recreate them. Idempotent-ish: skips a tool whose marker binary is
# already present.
#
#   AFNI  -> $DEST/abin   (3dvolreg: the volreg / motion-realignment standard)
#   FSL   -> $DEST/fsl    (mcflirt: volreg; flirt -cost bbr / epi_reg: BBR)
#
# After running, point the perf-bench providers at the tools (the wrappers read
# these, NOT $PATH -- robust to a missing shell profile):
#   export NPERF_AFNI_DIR=$DEST/abin
#   export NPERF_FSL_DIR=$DEST/fsl
# (the script appends these to $DEST/neuro_refs_env.sh for sourcing).
#
# Usage:  bash tools/setup_neuro_refs.sh [DEST]        # DEST default /scratch/nperf
#         AFNI_ONLY=1 bash tools/setup_neuro_refs.sh   # or FSL_ONLY=1
#
# Validated 2026-06-11 on Ubuntu 24.04 / glibc 2.39 / x86_64 with:
#   AFNI  26.1.04  (linux_ubuntu_24_64 -- the tarball is rolling "latest"; the
#                   version is recorded for provenance, not pinned in the URL)
#   FSL   ${FSL_VERSION}  (pinned via the installer's -V flag below)
set -euo pipefail

DEST="${1:-/scratch/nperf}"
AFNI_URL="https://afni.nimh.nih.gov/pub/dist/tgz/linux_ubuntu_24_64.tgz"
FSL_INSTALLER="https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py"
FSL_VERSION="${FSL_VERSION:-6.0.7.17}"   # pin for reproducibility (see header)
PYTHON="${NPERF_PYTHON:-/scratch/nperf/venv/bin/python}"

mkdir -p "$DEST" "$DEST/tmp"
export TMPDIR="$DEST/tmp"   # keep temp off the tiny root overlay

# -- AFNI: precompiled binaries (no tcsh needed to RUN 3dvolreg) --------------
if [ -z "${FSL_ONLY:-}" ]; then
  if [ -x "$DEST/abin/3dvolreg" ]; then
    echo "AFNI: 3dvolreg already present at $DEST/abin -- skipping."
  else
    echo "AFNI: downloading + extracting -> $DEST/abin"
    curl -fL --retry 3 -o "$DEST/afni_u24.tgz" "$AFNI_URL"
    rm -rf "$DEST/abin" && mkdir -p "$DEST/abin"
    # --no-same-owner: we are not the tarball's original uid; without it tar
    # aborts mid-extract on the first chown failure (incomplete install).
    tar --no-same-owner -xzf "$DEST/afni_u24.tgz" -C "$DEST/abin" \
        --strip-components=1
    rm -f "$DEST/afni_u24.tgz"
  fi
  "$DEST/abin/3dvolreg" -help >/dev/null 2>&1 \
    && echo "AFNI: 3dvolreg OK ($("$DEST/abin/afni" -ver 2>/dev/null | head -1))"
fi

# -- FSL: conda-based, self-contained (mcflirt + flirt -bbr + epi_reg) --------
if [ -z "${AFNI_ONLY:-}" ]; then
  if [ -x "$DEST/fsl/bin/mcflirt" ]; then
    echo "FSL: mcflirt already present at $DEST/fsl -- skipping."
  else
    echo "FSL: installing $FSL_VERSION -> $DEST/fsl (no shell mod, no CUDA)"
    curl -fL --retry 3 -o "$DEST/fslinstaller.py" "$FSL_INSTALLER"
    # -d dest, -n no-env, -r skip-registration, -c none skip-CUDA-libs,
    # -V pin the version. Non-interactive.
    "$PYTHON" "$DEST/fslinstaller.py" -d "$DEST/fsl" -n -r -c none \
        -V "$FSL_VERSION"
    rm -f "$DEST/fslinstaller.py"
  fi
  "$DEST/fsl/bin/mcflirt" 2>&1 | grep -qi mcflirt \
    && echo "FSL: mcflirt OK ($(cat "$DEST/fsl/etc/fslversion" 2>/dev/null))"
fi

# -- nibabel for the NIfTI round-trip wrappers (write array -> run -> read) ---
"$PYTHON" -c "import nibabel" 2>/dev/null \
  || "$PYTHON" -m pip install --quiet nibabel

# -- emit the env the perf-bench providers read ------------------------------
cat > "$DEST/neuro_refs_env.sh" <<EOF
# sourced by perf-bench runs to locate the community neuro refs (generated by
# tools/setup_neuro_refs.sh). The wrappers use these absolute dirs, not \$PATH.
export NPERF_AFNI_DIR="$DEST/abin"
export NPERF_FSL_DIR="$DEST/fsl"
export FSLDIR="$DEST/fsl"
export FSLOUTPUTTYPE=NIFTI_GZ
export PATH="$DEST/abin:$DEST/fsl/bin:\$PATH"
EOF
echo "wrote $DEST/neuro_refs_env.sh  (source it, or set NPERF_AFNI_DIR / NPERF_FSL_DIR)"
echo "DONE."
